# example values
server:
  port: 8081

spring:
  datasource:
    username: root
    password: Yura050595
    url: jdbc:mysql://localhost:3306/search_engine
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://liceum1.brestgoo.gov.by
      name: Liceum
    - url: https://www.skillbox.ru
      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
    - url: http://radiomv.ru
      name: Radiomv


user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
referrer: http://www.google.com

